### ISSUE TITLE
Consider distribution method for 3rd party open source licenses this project consumes

### ISSUE THREAD

**Issue by zionyx** [3shape/docker-ci#64]
I am starting to consume / copy / use codes from other open source projects. One example is from dotnet/roslyn with this license: https://github.com/dotnet/roslyn/blob/master/License.txt

This issue discusses on how to distribute 3rd party open source project licenses into our module.

**Comment by rasmusjelsgaard** [comment]
Not sure how to best solve this. I like the approach being discussed here: https://opensource.stackexchange.com/questions/2312/how-should-you-put-attribution-into-your-project

**Comment by zionyx** [comment]
Yes. It's as simple as this. This issue is a reminder to have it implemented this way or another.

VSCode has their licenses included here like this, License.html, `file:///C:/Program%20Files/Microsoft%20VS%20Code/resources/app/LICENSES.chromium.html`, provided you have VSCode x64 installed on Program Files.

One license file to bundle every open source license files is simple enough to automate.
